name: API Deploy to Production ECS

on:
    push:
        tags:
            - '*'
        paths:
            - 'api/**'
            - '.github/**'
            - 'infrastructure/aws/production/**'

jobs:
    deploy-production-ecs:
        runs-on: ubuntu-latest
        name: API Deploy to Production ECS
        environment: production

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Deploy API to Production
              uses: ./.github/actions/api-deploy-ecs
              with:
                github_access_token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
                aws_access_key_id: AKIARHES7IUAU2LR2B5K
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws_ecs_cluster_name: flagsmith-api-cluster-eu-west-2-f0b0108
                aws_ecs_cluster_arn: arn:aws:ecs:eu-west-2:084060095745:cluster/flagsmith-api-cluster-eu-west-2-f0b0108
                aws_ecs_service_name: flagsmith-svc-eu-west-2-c3cd356
                aws_vpc_subnet_id: subnet-40fd6629
                aws_ecs_security_group_id: sg-0ef0e8f66f890b80c
                aws_ecr_repository_arn: 084060095745.dkr.ecr.eu-west-2.amazonaws.com/flagsmith-ecr-934e8a7
                aws_identity_migration_event_bus_name: identity_migration-d46ed1a
                aws_identity_migration_event_bus_rule_id: identity_migration-b03c433
                aws_identity_migration_task_role_arn: arn:aws:iam::084060095745:role/task-exec-role-741a7e3
                aws_task_definitions_directory_path: infrastructure/aws/production
                flagsmith_saml_revision: v0.1.1
                flagsmith_workflows_revision: v1.0.2
                # Add auth controller

    run-tests:
        runs-on: ubuntu-latest
        name: Run E2E Tests
        environment: production
        needs: deploy-production-ecs

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Run E2E tests against production
              uses: ./.github/actions/e2e-tests
              with:
                e2e_test_token: ${{ secrets.E2E_TEST_TOKEN }}
                slack_token: ${{ secrets.SLACK_TOKEN }}
                environment: prod
